### ISSUE TITLE
Contribution and Coding Standards

### ISSUE THREAD

**Issue by gayanhewa** [btply/nodeshop#1]
Hi,

I am new to node.js , but I find this project interesting since I work mostly on Magento. I would like to discuss the coding standards and start to contribute to the project. Do advise.

Regards,

Gayan

**Comment by btply** [comment]
Hi Gayan!

Ive given you read and write access on c9.io, someone else has emailed me
about helping out as well and I´ve asked him to sign up as well. Just
thinking what to do about communication, maybe a google group?

Thanks,
Billy

On Tue, Jun 18, 2013 at 6:57 PM, Billy Topley billy.topley@gmail.comwrote:

> That's interesting, I'm from the UK so quite a distance! You can find the
> project at c9.io/btopley/nodeshop but you won't be able to edit it until
> I add you as a member, which I can't do right now as I am not at home. You
> will still be able to see all the code and get a feel for c9 from there
> though.
> 
> Thanks, Billy
> On 18 Jun 2013 15:42, "Gayan" notifications@github.com wrote:
> 
> > Well i'm from Colombo, Sri Lanka. I mostly work on PHP. But hoping to get
> > my hands dirty with node.js a bit.I signed up gayanhewa at gmail dot com.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/topley/nodeshop/issues/1#issuecomment-19615694
> > .

## 

Thanks, Billy

**Comment by gayanhewa** [comment]
Yeah that would make it easy

**Comment by btply** [comment]
Hi Gayan, I´ve made it at http://groups.google.com/group/nodeshop

On Mon, Jul 22, 2013 at 11:12 PM, Gayan notifications@github.com wrote:

> Yeah that would make it easy
> On Jul 23, 2013 3:36 AM, "Billy Topley" notifications@github.com wrote:
> 
> > Hi Gayan!
> > 
> > Ive given you read and write access on c9.io, someone else has emailed
> > me
> > about helping out as well and I´ve asked him to sign up as well. Just
> > thinking what to do about communication, maybe a google group?
> > 
> > Thanks,
> > Billy
> > 
> > On Tue, Jun 18, 2013 at 6:57 PM, Billy Topley billy.topley@gmail.comwrote:
> > 
> > > That's interesting, I'm from the UK so quite a distance! You can find
> > > the
> > > project at c9.io/btopley/nodeshop but you won't be able to edit it
> > > until
> > > I add you as a member, which I can't do right now as I am not at home.
> > > You
> > > will still be able to see all the code and get a feel for c9 from
> > > there
> > > though.
> > > 
> > > Thanks, Billy
> > > On 18 Jun 2013 15:42, "Gayan" notifications@github.com wrote:
> > > 
> > > > Well i'm from Colombo, Sri Lanka. I mostly work on PHP. But hoping to
> > > > get
> > > > my hands dirty with node.js a bit.I signed up gayanhewa at gmail dot
> > > > com.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/topley/nodeshop/issues/1#issuecomment-19615694>
> > > > .
> > 
> > ## 
> > 
> > Thanks, Billy
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/topley/nodeshop/issues/1#issuecomment-21379514>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/topley/nodeshop/issues/1#issuecomment-21379856
> .

## 

Thanks, Billy

**Comment by serendipities** [comment]
May i request viewing privileges on c9.io
