### ISSUE TITLE
When product is unavaliable render Error page

### ISSUE THREAD

**Issue by idx3d** [btply/nodeshop#2]
Hi! 
https://github.com/topley/nodeshop/blob/master/shop/routes/product.js#L16
Here if product not found in DB. Like this http://demo.nodeshop.org/product/apple-macbook-proa
or this http://demo.nodeshop.org/category/computersa

Program will drop with uncaughtError.

**Comment by btply** [comment]
Hi, 
This has now been fixed for the product controller and the category controller. Any categorys or products that cannot be matched to a URL will result in an error page.
