### ISSUE TITLE
Schemas description

### ISSUE THREAD

**Issue by idx3d** [btply/nodeshop#4]
@topley , Hello. 
Can you please describe your schemas?
You can just comment it out.

Thanks.

**Comment by idx3d** [comment]
@topley thanks. But i ask about fields. Can you help me, what is this field means (Product schema):

``` JavaScript
 make: { type: String, required: true }
```

**Comment by btply** [comment]
This is the definition for each key/value in the database, I'm using mongoose for data modelling and this is the mongoose schema. See the mongoose docs for more details on schemas and schema types.

**Comment by idx3d** [comment]
@topley thanks!
